# Generated by Django 2.2.5 on 2023-01-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221231_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='floor',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='تعداد طبقه'),
        ),
        migrations.AlterField(
            model_name='build',
            name='metr_b',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='زیربنا ساختمان'),
        ),
        migrations.AlterField(
            model_name='build',
            name='rooms',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='تعداد اتاق'),
        ),
        migrations.AlterField(
            model_name='garden',
            name='hektar_z',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' هکتار زمین'),
        ),
        migrations.AlterField(
            model_name='garden',
            name='inch',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='اینج آب'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='area',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='دهنه'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='metr',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='متراژ زمین'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='number',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='قطعه'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='status',
            field=models.BooleanField(default=False, verbose_name='وضعیت انتشار: '),
        ),
        migrations.AlterField(
            model_name='informations',
            name='tawn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='floor',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='تعداد طبقه'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='leas',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='اجاره'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='mortgae',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='رهن'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='rooms',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='تعداد اتاق'),
        ),
        migrations.AlterField(
            model_name='requester',
            name='floor',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='تعداد طبقه'),
        ),
        migrations.AlterField(
            model_name='requester',
            name='rooms',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='تعداد اتاق'),
        ),
    ]
